<x-app-layout>
    <html>

    <head>
        <title>Log Activity Lists</title>
        <!-- Add the output.css file generated by Tailwind CLI -->
        <link rel="stylesheet" href="/dist/output.css" />
    </head>

    <body>


        <div class="container mx-auto">
            <h1 class="my-8 text-4xl font-bold text-center">Log Activity Lists</h1>
            <table class="w-full border-collapse table-auto">
                <thead>
                    <tr class="text-sm font-medium text-left text-gray-700 rounded-lg">
                        <th class="px-4 py-2 bg-gray-200">No</th>
                        <th class="px-4 py-2 bg-gray-200">Subject</th>
                        <th class="px-4 py-2 bg-gray-200">URL</th>
                        <th class="px-4 py-2 bg-gray-200">Method</th>
                        <th class="px-4 py-2 bg-gray-200">Ip</th>
                        <th class="px-4 py-2 bg-gray-200" width="300px">User Agent</th>
                        <th class="px-4 py-2 bg-gray-200">User Id</th>

                    </tr>
                </thead>
                @if($logs->count())
                @foreach($logs as $key => $log)
                <tr class="text-sm font-normal text-gray-600">
                    <td class="px-4 py-2 border">{{ ++ $key }}</td>
                    <td class="px-4 py-2 border">{{ $log->subject }}</td>
                    <td class="px-4 py-2 text-green-500 border">{{ $log->url }}</td>
                    <td class="px-4 py-2 border"><span class="px-2 py-1 text-white bg-blue-500 rounded">{{ $log->method
                            }}</span></td>
                    <td class="px-4 py-2 text-yellow-600 border">{{ $log->ip }}</td>
                    <td class="px-4 py-2 text-red-600 border">{{ $log->agent }}</td>
                    <td class="px-4 py-2 border">{{ $log->user_id }}</td>

                </tr>
                @endforeach
            </table>
            <div class="d-flex justify-content-center">
                {{ $logs->links() }}
            </div>
            @endif
        </div>
    </body>

    </html>
</x-app-layout>